### ISSUE TITLE
Unknown module when browserifying the app

### ISSUE THREAD

**Issue by rexim** [kRITZCREEK/psc-gui#2]
I'm not an expert in this tech stack (started to use it today), so I may do something wrong. If so, please correct me.

When I try to browserify the app I see the following error:

```
$ npm install
... blah-blah ...
$ bower install
... blah-blah ...
$ pulp -w browserify --main Browser --to app.js
* Browserifying project in /home/rexim/Programming/foreign/psc-gui
* Building project in /home/rexim/Programming/foreign/psc-gui
Error found:
Error at /home/rexim/Programming/foreign/psc-gui/src/Node/Process.purs line 4, column 1 - line 5, column 1:
  Unknown module Debug.Trace
See https://github.com/purescript/purescript/wiki/Error-Code-UnknownModule for more information, or to contribute content related to this error.

* ERROR: Subcommand terminated with error code 1
```

Furthermore, when I checkout the previous commit 4378295c5b64abb7d53025bd593daa988f63ae35 everything works fine.

Looks like something was broken in c65a3a59e77cad5121c08633043079de843313a4

**Comment by kritzcreek** [comment]
Oh dear you found this... this project is just me fooling around at the moment. I'll make sure to clean up the build and provide instructions in the README tomorrow.

**Comment by rexim** [comment]
But this project is also a good place to try psc-ide on. :)

**Comment by kritzcreek** [comment]
yes it's true. I created this project so I could test psc-ide without needing an editor plugin. You can get around your current error by doing `bower install purescript-debug`. But maybe you will run into more errors...

**Comment by kritzcreek** [comment]
Should be fixed in master. Let me know if the dependencies still don't resolve.

**Comment by rexim** [comment]
I can only check that when I'm home, sorry. In 5 hours or so.

**Comment by rexim** [comment]
Everything works fine now, thanks!
