### ISSUE TITLE
Add README with a small instruction on how to set this up

### ISSUE THREAD

**Issue by rexim** [kRITZCREEK/psc-gui#3]
It's sooo unobvious for ones who never worked with purescript! I could only do that by extensive googling and watching the records of your streams. :) And #2 made this even worse! I did not understand what I was doing wrong.

It would be good at least to mention that you need [pulp](https://github.com/bodil/pulp) to get this working.

**Comment by kritzcreek** [comment]
Should be fixed in master. Let me know if the instructions give you any trouble.

**Comment by rexim** [comment]
Instructions are clear. Thank you! :)
